### ISSUE TITLE
No error messages seen when running under X

### ISSUE THREAD

**Issue by erco77** [corecoding/fonter#1]
The error messages printed to warn not to run under X aren't shown (running `./fonter` just returns a prompt).
It wasn't clear to me until I looked at the code the intention is to run the program in the linux console.

This appears to be due to the error message being printed with printf() while in curses `initscr()` mode, which apparently doesn't work.

The simple fix is to just swap the order of `printf("Error..")` and `endwin()` in the `error()` function, so the message is printed after curses is shut down. This way the message `please don't run fonter from X windows` can be seen.

Small patch attached.
[error-patch.txt](https://github.com/corecoding/fonter/files/5081155/error-patch.txt)

**Comment by corecoding** [comment]
I have updated the code. Thank you! I was a bit shocked to see a PR for this code, which I wrote in 1999. :) Kinda cool.
